In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
reg = linear_model.LinearRegression()
reg.fit(df[['area']].values,df.price)

LinearRegression()

In [4]:
reg.predict([[5000]])

array([859554.79452055])

In [5]:
import pickle

In [7]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [8]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [9]:
mp.predict([[5000]])

array([859554.79452055])

In [12]:
import joblib

In [13]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [14]:
mj = joblib.load('model_joblib')

In [15]:
mj.predict([[5000]])

array([859554.79452055])